export default {
  DemplotReport: 1,
  SocializationReport: 2,
  SuppliesFulfillment: 3,
  F5F6Report: 4,
  DistributorPositiveNews: 5,
  DistributorErdkk: 6,
  KioskPerformance: 7,
  FertilizerRedemption: 8,
  FertilizerDistribution: 9,
  KioskToFarmers: 10,
  F5ReportSubmission: 11,
  TPubersActivation: 12,
  KioskTransaction: 13,
  DistributorSanction: 14,
  DistributorCompliance: 15,
  DistributorReportCorrection: 16,
  DistributorActivity: 17,
  KioskStockFulfillment : 18,
}
