version: '3.7'

services:

  pi-distributor-managment-web-dev:
    image: pi-distributor-managment-web-dev
    container_name: pi-distributor-managment-web-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '6000:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
