export default {
    filled: {
        npwp: "99.999.999.9-999.999",
        npwp_issued_date: "09-03-2021",
        npwp_file_path: "/",
        business_entity_type: "PT",
        distributor_type: "Distributor",
        distributor_name: "Name",
        area_ids: [1, 2, 3],
        producer_ids: [1, 2, 3],
        president_director: "Name",
        company_email: "distributor@email.com",
        company_website: "distributor.com",
        address: "Long Address",
        province_id: 35,
        city_id: 3578,
        district_id: 357828,
        village_id: 3578281001,
        office_telp: "",
        pic_name: "PIC name",
        pic_phone_number: "+622100000",
        pic_email: "pic@email.com",
        pic_mobile_phone: "+62810000",
        pic_ktp_number: "11",
        pic_ktp_file_path: "/",
        address_phone_number: "+622100000"
    },
    cleared: {
        npwp: null,
        npwp_issued_date: null,
        npwp_file_path: null,
        business_entity_type: null,
        distributor_type: null,
        distributor_name: null,
        area_ids: null,
        producer_ids: null,
        president_director: null,
        company_email: null,
        company_website: null,
        address: null,
        province_id: null,
        city_id: null,
        district_id: null,
        village_id: null,
        office_telp: null,
        pic_name: null,
        pic_phone_number: null,
        pic_email: null,
        pic_mobile_phone: null,
        pic_ktp_number: null,
        pic_ktp_file_path: null,
        address_phone_number: null
    }
};
